name: Nexus to Pothos tests
on: [push, pull_request]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
      - run: pnpm test
