name: Nexus to Pothos tests
on: [push, pull_request]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      - run: yarn
      - run: yarn test